src/main/squarereact/src/components/Main.js
src/main/squarereact/src/index.js

Header_Navi 수정

---

src/main/squarereact/src/components/Main.js
src/main/squarereact/src/components/main.css

Navi 확장 축소 효과 추가

---

src/main/squarereact/src/components/Main.js
src/main/squarereact/src/components/PaymentManagement.js
src/main/squarereact/src/components/paymentManagement.css
src/main/squarereact/src/router/RouterMain.js

관리자 결제 관리 부분 좌측 우측 2개 컨테이너 프레임 생성

관리자 결제파트 컨테이너 생성

---

src/main/java/com/example/security/SecurityConfig.java

"react 파일 경로 해결 - 서버"

---

src/main/squarereact/src/components/Main.js
src/main/squarereact/src/router/RouterMain.js

경로 설정 임시 해제

---

src/main/java/com/example/controller/RouteController.java
src/main/java/com/example/controller/SubUserController.java
src/main/java/com/example/controller/UsersController.java
src/main/java/com/example/data/AcademiesEntity.java
src/main/java/com/example/data/JoinDto.java
src/main/java/com/example/repository/AcademiesRepository.java
src/main/java/com/example/repository/JoinService.java
src/main/java/com/example/repository/UsersRepository.java
src/main/resources/application.yml
src/main/squarereact/src/frame/Root.js
src/main/squarereact/src/member/JoinPage.jsx
src/main/squarereact/src/member/LoginPage.jsx
src/main/squarereact/src/member/StudentJoin.jsx
src/main/squarereact/src/member/SubCode.jsx
src/main/squarereact/src/member/SubUserRegistry.css
src/main/squarereact/src/member/SubUserRegistry.jsx
src/main/squarereact/src/router/RouterMain.js

+ 아이디에 사용되는 학원 식별 접두사 추가
+ 기존 코드 입력 후 계정 가입 시 아이디 자동 배정

서브계정 아이디 자동 생성(강사, 학부모)

---

src/main/java/com/example/classes/controller/ClassUsersController.java
src/main/java/com/example/classes/controller/ClassesController.java
src/main/java/com/example/classes/entity/ClassesEntity.java
src/main/java/com/example/classes/jpa/ClassUsersRepository.java
src/main/java/com/example/classes/jpa/ClassesRepository.java
src/main/java/com/example/classes/service/ClassUsersService.java
src/main/java/com/example/evaluations/entity/EvaluationsEntity.java
src/main/java/com/example/payment/controller/PaymentController.java
src/main/java/com/example/payment/jpa/PaymentGetClassRepository.java
src/main/java/com/example/user/controller/AcademyController.java
src/main/java/com/example/user/controller/SubUserController.java
src/main/java/com/example/user/controller/UsersController.java
src/main/java/com/example/user/dto/StudentDto.java
src/main/java/com/example/user/dto/TeacherDto.java
src/main/java/com/example/user/entity/AcademiesEntity.java
src/main/java/com/example/user/entity/ParentsEntity.java
src/main/java/com/example/user/entity/SchoolsEntity.java
src/main/java/com/example/user/entity/StudentsEntity.java
src/main/java/com/example/user/entity/TeachersEntity.java
src/main/java/com/example/user/jpa/StudentsRepository.java
src/main/java/com/example/user/jpa/TeachersRepository.java
src/main/java/com/example/user/service/StudentsService.java
src/main/squarereact/src/settings/ClassSetting.js

+ 클래스 관리 페이지 완성
+ 클래스 소속 학생들 백엔드 기본

클래스 관리 페이지 완성

---

src/main/java/com/example/jwt/JwtUtil.java
src/main/java/com/example/user/controller/UsersController.java
src/main/java/com/example/user/entity/UserAcademyResolver.java
src/main/java/com/example/user/entity/UsersEntity.java
src/main/squarereact/src/frame/Main.js
src/main/squarereact/src/router/RouterMain.js
src/main/squarereact/src/studentsManage/ClassStudentsManage.js

+ 유저 정보 불러오는 API 문제 
-> 다른 계정은 학원에 직접적인 연결 구조가 아니어서 몇 개 정보가 null로 불러와져 Exception 발생

하위계정 로그인 문제 해결

---

src/main/java/com/example/payment/controller/PaymentController.java
src/main/java/com/example/payment/jpa/PaymentService.java
src/main/squarereact/src/components/payment/PaymentManagement.js

로컬 서버에서 에러 없어 수업료 수정 일단 코드 커밋합니다

0527 1800 cws 수업료 수정 일단 커밋

---

src/main/java/com/example/classes/controller/ClassUsersController.java
src/main/java/com/example/classes/controller/ClassesController.java
src/main/java/com/example/classes/dto/RegisterResultDto.java
src/main/java/com/example/classes/service/ClassUsersService.java
src/main/java/com/example/user/controller/AcademyController.java
src/main/java/com/example/user/dto/StudentDto.java
src/main/java/com/example/user/jpa/StudentsRepository.java
src/main/java/com/example/user/service/StudentsService.java
src/main/squarereact/src/frame/Main.js
src/main/squarereact/src/studentsManage/ClassStudentsManage.js
src/main/squarereact/src/studentsManage/classStudentsManage.css
src/main/squarereact/src/ui/Modal.jsx

+ 수강생 관리 페이지 API 연결
1. 학원 내 학생 목록 띄우기
2. 클래스 별 필터링 및 이름 검색
3. 클래스에 학생 추가
4. 클래스에서 학생 삭제

수강생 관리 페이지 완

---

src/main/java/com/example/classes/controller/ClassesController.java
src/main/squarereact/src/settings/ClassSetting.js
src/main/squarereact/src/studentsManage/ClassStudentsManage.js

클래스 목록 API 강사계정 접근 가능

---

src/main/squarereact/src/attendBook/AttendParent.js
src/main/squarereact/src/attendBook/AttendStu.js

빌드 테스트를 위한 주석..

---

src/main/squarereact/src/attendBook/AttendParent.js
src/main/squarereact/src/evaluations/TotalEvaluationsAdmin.js

CI/CD 주석
Line 16:11:  'handleSelectStudent' is assigned a value but never used  no-unused-vars
Line 22:11:  'token' is assigned a value but never used                no-unused-vars
Line 62:21:  'userId' is assigned a value but never used               no-unused-vars
Line 62:29:  'role' is assigned a value but never used                 no-unused-vars
=> 주석 처리

빌드테스트 2 - 주석

---

src/main/java/com/example/schedule/controller/ScheduleController.java
src/main/java/com/example/schedule/dto/ScheduleResponse.java
src/main/java/com/example/schedule/dto/ScheduleSaveRequest.java
src/main/java/com/example/schedule/dto/SchoolsSimpleDto.java
src/main/java/com/example/schedule/entity/ScheduleEntity.java
src/main/java/com/example/schedule/entity/ScheduleType.java
src/main/java/com/example/schedule/entity/SchoolsEntity.java
src/main/java/com/example/schedule/entity/SchoolsScheduleEntity.java
src/main/java/com/example/schedule/jpa/ScheduleRepository.java
src/main/java/com/example/schedule/jpa/SchoolsRepository.java
src/main/java/com/example/schedule/jpa/SchoolsScheduleRepository.java
src/main/java/com/example/schedule/service/ScheduleService.java
src/main/java/com/example/user/controller/SubUserController.java
src/main/java/com/example/user/entity/AcademiesEntity.java
src/main/java/com/example/user/entity/StudentsEntity.java
src/main/squarereact/package-lock.json
src/main/squarereact/package.json
src/main/squarereact/src/academycaller/AcademyCaller.css
src/main/squarereact/src/academycaller/AcademyCaller.jsx
src/main/squarereact/src/academycaller/index.js
src/main/squarereact/src/evaluations/TotalEvaluationsAdmin.js
src/main/squarereact/src/frame/Main.js
src/main/squarereact/src/member/SubCode.jsx
src/main/squarereact/src/member/SubUserRegistry.jsx
src/main/squarereact/src/router/RouterMain.js

1. 학원 일정 등록 API 연결
2. 학원 스케줄 달력에 띄우기
서브코드 입력 버그 수정 <- URI 인코딩 문제

학원 캘린더 - 스케줄 1차 기능 적용

---

src/main/java/com/example/schedule/controller/ScheduleController.java
src/main/java/com/example/schedule/dto/ScheduleDateUpdateRequest.java
src/main/java/com/example/schedule/dto/ScheduleUpdateRequest.java
src/main/java/com/example/schedule/service/ScheduleService.java
src/main/squarereact/src/academycaller/AcademyCaller.css
src/main/squarereact/src/academycaller/AcademyCaller.jsx
src/main/squarereact/src/frame/Main.js
src/main/squarereact/src/member/SubUserRegistry.jsx
src/main/squarereact/src/server.js
src/main/squarereact/src/websocket/socket.js

1. 일정만 변경하는 API
2. 내용 전부 변경하는 API

Jojindragon

---

src/main/java/com/example/timetable/controller/TimetableController.java
src/main/java/com/example/timetable/dto/TimecontentsDto.java
src/main/java/com/example/timetable/dto/TimetableRequestDto.java
src/main/java/com/example/timetable/dto/TimeusersDto.java
src/main/java/com/example/timetable/entity/TimecontentsEntity.java
src/main/java/com/example/timetable/entity/TimetableEntity.java
src/main/java/com/example/timetable/entity/TimeusersEntity.java
src/main/java/com/example/timetable/repository/TimetableRepository.java
src/main/java/com/example/timetable/service/TimetableService.java
src/main/java/com/example/user/controller/TeachersController.java
src/main/java/com/example/user/jpa/TeachersRepository.java
src/main/java/com/example/user/service/TeachersService.java
src/main/squarereact/src/frame/Main.js
src/main/squarereact/src/timetable/CreateTimetable.js
src/main/squarereact/src/timetable/Timetable.js
src/main/squarereact/src/timetable/createTimetable.css

react : CreateTimetable.js, createTimetable.css 완료
DTO : TimecontentsDto.java, TimeusersDto.java, TimetableRequestDto.java
Entity : TimecontentsEntity.java, TimetableEntity.java, TimeusersEntity.java
위 파일들은 내용 작성 완료한 파일입니다.
TimetableRepository, TimetableService, TimetableController 이 파일들은 내용이 없는 파일로 추후 내용 추가 예정입니다.

시간표생성 프론트 완료 및 Entity, Dto 작성

---

src/main/java/com/example/classes/jpa/ClassUsersRepository.java
src/main/java/com/example/timetable/controller/TimetableController.java
src/main/java/com/example/timetable/dto/TimecontentsDto.java
src/main/java/com/example/timetable/dto/TimetableRequestDto.java
src/main/java/com/example/timetable/entity/TimecontentsEntity.java
src/main/java/com/example/timetable/entity/TimetableEntity.java
src/main/java/com/example/timetable/repository/TimecontentsRepository.java
src/main/java/com/example/timetable/repository/TimetableRepository.java
src/main/java/com/example/timetable/repository/TimeusersRepository.java
src/main/java/com/example/timetable/service/TimetableService.java
src/main/squarereact/src/timetable/CreateTimetable.js

react : CreateTimetable.js, createTimetable.css 수정
Repository : TimetableRepository, TimecontentsRepository, TimeusersRepository  생성 및 수정
Service : TimetableService 수정
Controller : TimetableController 수정

시간표 등록 기능 완료

---

src/main/java/com/example/payment/controller/PaymentController.java
src/main/java/com/example/payment/dto/PaymentGetChildrenDto.java
src/main/java/com/example/payment/jpa/PaymentChildrenRepository.java
src/main/java/com/example/payment/jpa/PaymentGetClassRepository.java
src/main/java/com/example/payment/service/PaymentService.java
src/main/squarereact/src/frame/Main.js
src/main/squarereact/src/payment/PaymentPayCheck.js
src/main/squarereact/src/router/RouterMain.js

- roleId 신설에 맞춰서 PaymentPayCheck.js 라우팅을 수정
- 컨트롤러에서 학부모가 자신의 자녀를 get할 수 있는 로직 추가
자세한 내역은 아래 링크에서 확인할 수 있습니다.
https://www.notion.so/ceyemong/1f552a00d4f28097a9c8c9c9a71d6a8d?pvs=97#20952a00d4f2801d8780c867c7676ed3

0605 1700 결제파트 학부모 수강신청 자녀매핑까지 완료

---

src/main/java/com/example/schedule/controller/ScheduleController.java
src/main/java/com/example/schedule/jpa/SchoolsScheduleRepository.java
src/main/java/com/example/schedule/service/ScheduleService.java
src/main/squarereact/src/academycaller/AcademyCaller.css
src/main/squarereact/src/academycaller/AcademyCaller.jsx
src/main/squarereact/src/studentsManage/classStudentsManage.css

- 수정 & 삭제 권한별 작업 완료
- Navi 가려짐 현상 수정 완료

06월 첫째주 작업

---

src/main/java/com/example/classes/controller/ClassesController.java
src/main/java/com/example/classes/dto/ClassResponse.java
src/main/java/com/example/classes/jpa/ClassCountProjection.java
src/main/java/com/example/classes/jpa/ClassUsersRepository.java
src/main/squarereact/src/settings/ClassSetting.js

클래스 관리 페이지 현재 학생 수 적용

---

src/main/squarereact/package-lock.json
src/main/squarereact/package.json
src/main/squarereact/src/evaluations/EvaluationsParents.css
src/main/squarereact/src/evaluations/EvaluationsParents.js
src/main/squarereact/src/evaluations/TotalEvaluationsAdmin.css
src/main/squarereact/src/evaluations/TotalEvaluationsAdmin.js

TotalEvaluationsAdmin.js, EvaluationParent.js 프론트 수정

종합 평가 페이지 CSS 수정

---

src/main/java/com/example/payment/controller/PaymentController.java
src/main/java/com/example/payment/dto/PaymentEnrollDto.java
src/main/java/com/example/payment/entity/EnrollEntity.java
src/main/java/com/example/payment/jpa/PaymentEnrollRepository.java
src/main/java/com/example/payment/service/PaymentService.java
src/main/squarereact/src/payment/PaymentPayCheck.js

0606~0609 결제파트 PR

---

src/main/squarereact/src/academycaller/AcademyCaller.css
src/main/squarereact/src/academycaller/AcademyCaller.jsx
src/main/squarereact/src/attendBook/Attend.js
src/main/squarereact/src/attendBook/AttendParent.js
src/main/squarereact/src/attendBook/AttendStu.js
src/main/squarereact/src/attendBook/attend.css
src/main/squarereact/src/attendBook/attendanceChartOptions.js
src/main/squarereact/src/studentsManage/classStudentsManage.css

출석 관리 - 누적 출석률 그래프 1차 출력

---

src/main/java/com/example/payment/controller/PaymentController.java
src/main/java/com/example/payment/dto/PaymentEnrollDto.java
src/main/java/com/example/payment/dto/PaymentEnrollOutputDto.java
src/main/java/com/example/payment/entity/EnrollEntity.java
src/main/java/com/example/payment/jpa/PaymentEnrollRepository.java
src/main/java/com/example/payment/jpa/PaymentGetClassRepository.java
src/main/java/com/example/payment/service/PaymentService.java
src/main/squarereact/src/payment/PaymentPayCheck.css
src/main/squarereact/src/payment/PaymentPayCheck.js

자세한 작업 내역은
- https://www.notion.so/ceyemong/1f552a00d4f28097a9c8c9c9a71d6a8d?pvs=97#20652a00d4f2808790faffe666c1f7e0
- 에서 확인 가능

결제파트 1850 장바구니 프론트까지 구현

---

src/main/squarereact/package-lock.json
src/main/squarereact/package.json
src/main/squarereact/src/attendBook/Attend.js
src/main/squarereact/src/attendBook/AttendStu.js
src/main/squarereact/src/server.js
src/main/squarereact/src/websocket/socket.js

웹소켓 → Socket.IO 구조로 변경 1차본

---

logs/app.log
src/main/java/com/example/attend/controller/AttendanceController.java
src/main/java/com/example/attend/dto/StartAttendanceResponseDto.java
src/main/java/com/example/attend/entity/AttendanceCodeEntity.java
src/main/java/com/example/attend/entity/AttendancesEntity.java
src/main/java/com/example/attend/entity/TimetableAttendEntity.java
src/main/java/com/example/attend/repository/AttendanceCodeRepository.java
src/main/java/com/example/attend/repository/AttendancesRepository.java
src/main/java/com/example/attend/repository/TimetableAttendRepository.java
src/main/java/com/example/attend/service/AttendanceService.java
src/main/java/com/example/timetable/entity/TimetableEntity.java
src/main/java/com/example/user/entity/StudentsEntity.java
src/main/squarereact/package-lock.json
src/main/squarereact/package.json
src/main/squarereact/src/attendBook/Attend.js
src/main/squarereact/src/attendBook/AttendStu.js
src/main/squarereact/src/member/LoginPage.jsx
src/main/squarereact/src/mobile/MobileCalendar.jsx
src/main/squarereact/src/mobile/MobileNavi.jsx
src/main/squarereact/src/mobile/index.js
src/main/squarereact/src/mobile/mobileCalendar.css
src/main/squarereact/src/mobile/mobileNavi.css
src/main/squarereact/src/router/RouterMain.js

- npm install 필요
- 왠만하면 timetableAttend 테이블 PK 값을 가져와서 할 것

모바일 1차 작업 및 출결 해결

---

src/main/java/com/example/classes/controller/ClassesController.java
src/main/java/com/example/evaluations/controller/EvaluationsController.java
src/main/java/com/example/timetable/controller/TimetableController.java
src/main/java/com/example/timetable/service/TimetableService.java
src/main/squarereact/package-lock.json
src/main/squarereact/package.json
src/main/squarereact/src/evaluations/EvaluationStudent.css
src/main/squarereact/src/evaluations/EvaluationStudent.js
src/main/squarereact/src/evaluations/EvaluationsParents.css
src/main/squarereact/src/evaluations/EvaluationsParents.js
src/main/squarereact/src/evaluations/TotalEvaluationsAdmin.js
src/main/squarereact/src/timetable/CreateTimetable.js
src/main/squarereact/src/timetable/Timetable.js
src/main/squarereact/src/timetable/createTimetable.css
src/main/squarereact/src/timetable/timetable.css

npm install : bootstrap
수정 및 생성한 파일들 
React :  CreateTimetable.js, createTimetable.css, Timetable.js, timetable.css, EvaluationStudent.js, evaluationStudent.css, EvaluationsParents.js, evaluationsParents.css
Controller : TimetableController
Service : TimetableService

시간표 및 종합평가 수정

---

src/main/squarereact/src/mobile/MobileMypage.jsx
src/main/squarereact/src/mobile/MobileNavi.jsx
src/main/squarereact/src/mobile/MobileTimetable.jsx
src/main/squarereact/src/mobile/index.js
src/main/squarereact/src/mobile/mobileMypage.css
src/main/squarereact/src/mobile/mobileTimetable.css
src/main/squarereact/src/router/RouterMain.js
src/main/squarereact/src/timetable/Timetable.js
src/main/squarereact/src/timetable/timetable.css

수정 및 생성한 파일들 
React :  MobileNavi.jsx, RouterMain.js,  MobileMypage.jsx, mobileMypage.css, MobileTimetable.jsx, mobileTimetable.css, Timetable.js, timetable.css

모바일 마이페이지, 일정관리 완료

---

src/main/java/com/example/attend/controller/AttendanceController.java
src/main/java/com/example/attend/service/AttendanceHistoryService.java
src/main/java/com/example/timetable/controller/TimetableController.java
src/main/java/com/example/timetable/repository/TimecontentsRepository.java
src/main/java/com/example/timetable/service/TimetableService.java
src/main/squarereact/src/attendBook/Attend.js

지난 출석 리스트 수정

---

src/main/squarereact/src/mobile/MobileTimetable.jsx
src/main/squarereact/src/payment/paymentManagement.css
src/main/squarereact/src/timetable/Timetable.js

수정 및 생성한 파일들 
React :  mobileTimetable.css, PaymentManagement.css, Timetable.js

시간표 오늘 버튼 기능 수정

---

src/main/squarereact/src/timetable/UpdateTimetable.js

수정 및 생성한 파일 
React : UpdateTimetable.js

시간표 수정페이지 스크롤 되도록 수정

---

src/main/squarereact/src/Board/Notice/BoardMainPostDetail.js
src/main/squarereact/src/Board/Notice/BoardMainPostForm.js

react 오류 해결

---

src/main/squarereact/src/payment/PaymentManagement.js
src/main/squarereact/src/payment/PaymentPayCheck.js

관리자 수강료 관리 페이지 디자인
학부모 기존 결제 내역 테이블 중 혼선을 피하기 위해 각 결제한 수업의 기간 표시

0618 1837 결제파트 디자인 수정

---

src/main/squarereact/src/payment/PaymentManagement.js

관리자 페이지에서 수업료를 수정하기 위해 수업료 부분을 클릭해서 수정하는 것으로 바궜습니다.

0618 1856 수업료 수정 클릭 부분 수정
